services:
  - type: web
    name: lockbox
    env: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn lockbox.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lockbox_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0